platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

target 'QTAuth_Example' do
  pod 'QTAuth',  :path => '../', :inhibit_warnings => false

  target 'QTAuth_Tests' do
    inherit! :search_paths

    
  end
end
